#ifndef AXLEUTIL_TRACING_WRAPPER_
#define AXLEUTIL_TRACING_WRAPPER_

#ifdef AXLE_UTIL_TRACING_ENABLE
#define TRACING_ENABLE
#include <Tracer/trace.h>

#define AXLE_UTIL_TELEMETRY_FUNCTION() STACKTRACE_FUNCTION(); TRACING_FUNCTION()
#define AXLE_UTIL_TELEMETRY_SCOPE(name) STACKTRACE_SCOPE(name); TRACING_SCOPE(name)
#else
#define AXLE_UTIL_TELEMETRY_FUNCTION() STACKTRACE_FUNCTION()
#define AXLE_UTIL_TELEMETRY_SCOPE(name) STACKTRACE_SCOPE(name)
#endif
#endif

